### PR TITLE
Refactor and update deps

### PR DESCRIPTION
**Pull request by chauthai**
Added linting rules; refactored according to linting rules;
introduced deviceName property in settings; updated dependencies

### CODE REVIEW

**Comment by vrunoa** [comment]
interesting @chauthai . I'll take a deep look tonight and merge the PR

**Comment by chauthai** [comment]
@vrunoa I think the PR was to early. I'm still struggling to activate es7 async await in babel for mocha.
Maybe you can help me out.
I want to use:

test1.js
```javascript
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
chai.should();
var wd = require('wd');
var argv = require('minimist')(process.argv.slice(2));
var caps = require('./'+argv.platform+'.json');

chaiAsPromised.transferPromiseness = wd.transferPromiseness;

describe('Test example tests', function() {
  this.timeout(0);

  describe("Checking all elements are displayed", function() {
    var browser;
    
    before(function() {
      browser = wd.promiseChainRemote(caps);
      return browser
        .init(caps);
    });

    after(function() {
      return browser
        .quit();
    });
    
    it("should show hello world", async function(done) {
      const contexts = await browser.contexts();
      await browser.context(contexts[1]);
      browser
      .setImplicitWaitTimeout(10000)
      .elementByClassName("hello")
      .isDisplayed()
      .then(function(isDisplayed){
        isDisplayed.should.equal(true)
      })
      .nodeify(done);
    });

    it("should show h1", async function(done) {
      const contexts = await browser.contexts();
      await browser.context(contexts[1]);
      browser
      .setImplicitWaitTimeout(10000)
      .elementByTagName("h1")
      .isDisplayed()
      .then(function(isDisplayed){
        isDisplayed.should.equal(true)
      })
      .nodeify(done);
    });
  
  });

});
```
These two lines are important:
```
const contexts = await browser.contexts();
await browser.context(contexts[1]);
```
And `async/await` in general is very useful to have :-)

**Comment by chauthai** [comment]
I successfully changed the runTest method to use babel with mocha when the `--babel` flag is activated.
`async/await` is now available in the tests of the target project.

**Comment by vrunoa** [comment]
@chauthai nice work. I'll change to use ```path.join``` instead of ```glue``` and update the node version.

**Pull request merged**
